[platformio]
default_envs = proto_213

[env]
platform = espressif8266
board = esp8285
framework = arduino
lib_deps =
  zinggjm/GxEPD2
upload_speed = 115200
upload_resetmethod = nodemcu
monitor_speed = 115200

[env:proto_213]
build_src_filter =
  +<main_213.cpp>

[env:proto_154]
build_src_filter =
  +<main_154.cpp>
